# Generated by Django 3.2.11 on 2022-01-06 10:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
